#pragma once

#define CHARYBDIS_ENABLE_POINTER_ACCELERATION
#define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER
#define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_THRESHOLD 1
#ifdef ROTATIONAL_TRANSFORM_ANGLE
    #undef ROTATIONAL_TRANSFORM_ANGLE
    #define ROTATIONAL_TRANSFORM_ANGLE -65
#endif
