#pragma once

#ifdef CHARYBDIS_AUTO_SNIPER_LAYER
#    undef CHARYBDIS_AUTO_SNIPER_LAYER
#    define CHARYBDIS_AUTO_SNIPER_LAYER 4
#endif
#define CHARYBDIS_DRAGSCROLL_INVERT_Y
#define CHARYBDIS_TRACKBALL_SPEED_DIVIDER_Y 8
#define CHARYBDIS_TRACKBALL_SPEED_DIVIDER_X 12
