#pragma once

#ifdef OLED_DRIVER_ENABLE
  #define OLED_DISPLAY_128X64
#endif

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_ANIMATIONS
  #define RGBLIGHT_HUE_STEP 8
  #define RGBLIGHT_SAT_STEP 8
  #define RGBLIGHT_VAL_STEP 8
#endif

#define FORCE_NKRO
#define TAPPING_TERM 150

#define MOUSEKEY_DELAY 150
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_TIME_TO_MAX 150
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define QMK_KEYS_PER_SCAN 4
#define USE_POLLING_INTERVAL_MS 1
