#pragma once

#ifdef OLED_DRIVER_ENABLE
  #define OLED_DISPLAY_128X64
#endif

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_ANIMATIONS
  #define RGBLIGHT_HUE_STEP 8
  #define RGBLIGHT_SAT_STEP 8
  #define RGBLIGHT_VAL_STEP 8
#endif

#define FORCE_NKRO
#define TAPPING_TERM 150
#define TAP_CODE_DELAY 25

#define MOUSEKEY_INTERVAL 16
#define QMK_KEYS_PER_SCAN 4
#define USE_POLLING_INTERVAL_MS 1
