#pragma once

#define FORCE_NKRO
#define TAPPING_TERM 150
#define TAP_CODE_DELAY 25

#define EE_HANDS
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 64
#define QMK_KEYS_PER_SCAN 4
#define USE_POLLING_INTERVAL_MS 1
