#pragma once

#ifdef TAPPING_TERM
#    undef TAPPING_TERM
#    define TAPPING_TERM 150
#endif

#define TAPPING_TERM_PER_KEY
#define TAP_CODE_DELAY 50
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define PERMISSIVE_HOLD
#define USB_POLLING_INTERVAL_MS 1
