#pragma once

#define MASTER_LEFT
#define USE_SERIAL_PD2
#define SSD1306OLED

#define FORCE_NKRO
#define TAPPING_TERM 150
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#ifndef NO_DEBUG
#define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT
#endif // !NO_PRINT

#ifdef RGBLIGHT_ENABLE
    #undef RGBLED_NUM
    #define RGBLIGHT_ANIMATIONS
    #define RGBLED_NUM 27
    #define RGBLIGHT_LIMIT_VAL 120
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
#endif

#define MOUSEKEY_DELAY 150
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_TIME_TO_MAX 150
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define QMK_KEYS_PER_SCAN 4
#define USE_POLLING_INTERVAL_MS 1
#define ONESHOT_TIMEOUT 1000
#define IGNORE_MOD_TAP_INTERRUPT