#pragma once

#define MASTER_LEFT
#define USE_SERIAL_PD2
#define SSD1306OLED

#define FORCE_NKRO
#define TAPPING_TERM 150
#define TAP_CODE_DELAY 25
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#ifndef NO_DEBUG
#define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT
#endif // !NO_PRINT

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 64
#define QMK_KEYS_PER_SCAN 4
#define USE_POLLING_INTERVAL_MS 1
