#pragma once

#define MASTER_LEFT
#define USE_SERIAL_PD2
#define SSD1306OLED

#define FORCE_NKRO
#define TAPPING_TERM 150
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#ifndef NO_DEBUG
#define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT
#endif // !NO_PRINT

#define MOUSEKEY_DELAY 150
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_TIME_TO_MAX 150
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define QMK_KEYS_PER_SCAN 4
#define USE_POLLING_INTERVAL_MS 1
